### PR TITLE
preliminary NodeJS stuff

### PR DESCRIPTION
**Pull request by kentjhall**
Now NodeJS dep can be installed with `npm install`; specifically doesn't track the `node_modules` folder that is created.

### CODE REVIEW

**Review by JamesYang007 — COMMENTED** [review]
Do these json files must live in the root dir? Idk what the standard structure is for this. It seems so based on the content but just making sure.

LGTM

**Comment by kentjhall** [comment]
just moved these files to folder called "nodejs_scripts" so that they are no longer in root directory (I think it does make more sense this way—this folder is where the .js scripts will be kept as well)

**Comment by JamesYang007** [comment]
Wait but now you can't do `npm install` you gotta go into this directory first before running that command. Are we cool with that

**Comment by kentjhall** [comment]
yeah ofc, because the deps are installed in that directory. we don't need the node_modules deps to be installed at the root of the project. can revert if you'd prefer though, it was kinda convenient having the command at the root of the project (we could also always j write a shell script for this later on, if/when the directory structure gets more complex)

**Comment by kentjhall** [comment]
also, can do from root with `npm install --prefix nodejs_scripts`

**Review by JamesYang007 — APPROVED** [review]
LGTM

**Pull request merged**
